/**
 * E2E Test: Complete Challenge Workflow
 * Tests the full user journey from login to completing a challenge
 * 
 * Flow: Login → Create Goal → View Challenges → Start Challenge → Mark Complete
 */

describe('Complete Challenge Workflow', () => {
  const testUser = {
    email: `cypress-test-${Date.now()}@example.com`,
    password: 'CypressTest123!',
    firstName: 'Cypress',
    lastName: 'Tester'
  };

  const testGoal = {
    title: 'Learn React Testing',
    description: 'Master Cypress E2E testing with React applications',
    category: 'web-development',
    difficulty: 'medium'
  };

  before(() => {
    // Register a new user for testing
    cy.visit('/signup');
    cy.get('input[name="firstName"]').type(testUser.firstName);
    cy.get('input[name="lastName"]').type(testUser.lastName);
    cy.get('input[name="email"]').type(testUser.email);
    cy.get('input[name="password"]').type(testUser.password);
    cy.get('input[name="confirmPassword"]').type(testUser.password);
    cy.get('button[type="submit"]').click();
    
    // Wait for successful registration and redirect
    cy.url().should('not.include', '/signup');
  });

  it('should complete full workflow: login → create goal → start challenge → mark complete', () => {
    // Step 1: Login
    cy.log('Step 1: Logging in');
    cy.visit('/login');
    cy.get('input[name="email"], input[type="email"]').clear().type(testUser.email);
    cy.get('input[name="password"], input[type="password"]').clear().type(testUser.password);
    cy.get('button[type="submit"]').click();
    
    // Verify successful login - should redirect to dashboard
    cy.url().should('include', '/dashboard');
    cy.contains(testUser.firstName).should('be.visible');

    // Step 2: Create a Goal
    cy.log('Step 2: Creating a goal');
    cy.visit('/goals');
    
    // Click create goal button (works both for first goal and additional goals)
    cy.contains('button', /create|new goal/i, { timeout: 10000 }).click();
    
    // Wait for modal to appear and fill out goal form
    cy.get('input[placeholder*="Master React"]', { timeout: 5000 }).clear().type(testGoal.title);
    cy.get('textarea[placeholder*="learn"]').clear().type(testGoal.description);
    cy.get('select').first().select(testGoal.category);
    cy.get('select').eq(1).select(testGoal.difficulty);
    
    // Submit goal form
    cy.contains('button', /create goal|save/i).click();
    
    // Verify goal was created
    cy.contains(testGoal.title, { timeout: 10000 }).should('be.visible');

    // Step 3: Navigate to Challenges and verify they were generated
    cy.log('Step 3: Viewing AI-generated challenges');
    cy.visit('/challenges');
    
    // Wait for challenges to load (they are generated by AI)
    cy.get('.bg-white.rounded-2xl.p-6', { timeout: 15000 })
      .should('have.length.at.least', 1);
    
    // Verify we have the progress bar
    cy.contains('Your Progress').should('be.visible');

    // Step 4: Start a Challenge
    cy.log('Step 4: Starting a challenge');
    
    // Find and click the "Start Challenge" button on the first challenge
    cy.contains('button', 'Start Challenge').first().click();
    
    // Verify challenge status changed to "In Progress"
    cy.contains('In Progress', { timeout: 10000 }).should('be.visible');

    // Step 5: Mark Challenge as Complete
    cy.log('Step 5: Marking challenge as complete');
    
    // Click "Mark Complete" button
    cy.contains('button', 'Mark Complete').first().click();
    
    // Verify challenge status changed to "Completed"
    cy.contains('✓ Completed', { timeout: 10000 }).should('be.visible');

    // Step 6: Verify Progress Bar Updated
    cy.log('Step 6: Verifying progress bar update');
    
    // Check that progress bar shows at least 33% (1 out of 3 challenges completed)
    cy.contains('1 of').should('be.visible');
    cy.contains(/33%|34%/).should('be.visible');
  });

  it('should prevent marking incomplete challenges as complete', () => {
    cy.visit('/challenges');
    
    // Wait for challenges to load
    cy.get('.bg-white.rounded-2xl.p-6', { timeout: 10000 })
      .should('have.length.at.least', 1);
    
    // "Mark Complete" button should not be visible for un started challenges
    // Only "Start Challenge" should be visible
    cy.contains('button', 'Start Challenge').should('exist');
  });

  it('should show correct challenge count and completion status', () => {
    cy.visit('/challenges');
    
    // Wait for challenges to load
    cy.get('.bg-white.rounded-2xl.p-6', { timeout: 10000 })
      .should('have.length.at.least', 1);
    
    // Verify we have challenges (AI should generate 3 per goal)
    cy.get('.bg-white.rounded-2xl.p-6')
      .should('have.length', 3);
    
    // Verify progress information is displayed
    cy.contains('Your Progress').should('be.visible');
    cy.contains(/\d+ of \d+ challenges completed/).should('be.visible');
  });
});
